### ISSUE TITLE
Topseller Slider Problem

### ISSUE THREAD

**Issue by tpierschel** [NetInventors/sw.ext.neti_tool_kit#17]
Aus: https://forum.shopware.com/messages/19534#Message_23265

Es freut mich sehr das bei euchem Toolkit Plugin nun die Möglichkeit besteht Eigenschaften auch in den SHopware Slider auszugeben. Es löst bei mir im Shop ein Problem:

https://www.shisha-dreams.de/shisha-tabak/bluehorse/

Das Plugin arbeitet auch soweit. Nur leider funktioniert es bei mir nicht bei dem Top Seller Slider. Bei ähnliche Artikel und Kunden kauften auch funktioniert es. (zumindest gröstenteils)

**Comment by hrombach** [comment]
Ist behoben mit #16 und released mit 2.2.1.
