### ISSUE TITLE
Property Eigenschaften überall verfügbar machen

### ISSUE THREAD

**Issue by tpierschel** [NetInventors/sw.ext.neti_tool_kit#7]
Waere super wenn man die Property Eigenschaften, auch in den Top-Seller Box, Kunden kauften auch.., Aehnliche Artikel etc. wiedergeben koennte. Und nicht nur im listing.

https://forum.shopware.com/discussion/38177/plugin-shopware-toolkit#latest

**Comment by sbrueggenolte** [comment]
@tpierschel Die Version 2.2.0 wurde released.
In den Plugin-Einstellungen können nun die Artikel-Eigenschaften auch an folgenden Stellen zugeschaltet werden:
- Topseller
- Ähnliche Artikel
- Gekaufte Artikel
